### ISSUE TITLE
GlobalUI.toast(text, html) shifted to toast(test, html)

### ISSUE THREAD

**Issue by HedCET** [HedCET/torrent_watch#25]
torrentz_db available globally, that is used in both menu and list, after edit in that just call re_render()

**Comment by arunhedcet** [comment]
No need to add new toast for every error. This is against the concept of using global elements to show toast,refresh spinner,dialog etc

**Comment by HedCET** [comment]
what happen when multiple toast comes, ex - delete more items with in 2000 timedelay

**Comment by HedCET** [comment]
undo_hidden_callback() modify to take array of _id
